### ISSUE TITLE
support creating DataFrame with Series with different index

### ISSUE THREAD

**Issue by alexcwyu** [rsheftel/raccoon#10]
say I have 2 timeseries with different index

## TimeSeries1
  timestamp      close
          0  0.582778
          2  0.682441
          4  0.0365585
          6  0.549261
          8  0.0575284

## TimeSeries2
  timestamp       open
          0  0.525396
          1  0.380595
          2  0.399267
          3  0.309334
          4  0.339246
          5  0.91433
          6  0.30177
          7  0.814401
          8  0.722506
          9  0.0100632

does Raccoon support the creation of Dataframe from them?
it doesn't look like it is support this but let me know if I am wrong

**Comment by alexcwyu** [comment]
my current solution is extending the rc.DataFrame:

`class DataFrame(rc.DataFrame):
    def __init__(self, series_list=None):
        all_index = set()
        #data = {}
        columns = []

        for series in series_list:
            all_index |= set(series.index)
            columns.append(series.id)

        index = sorted(all_index)

        super(DataFrame, self).__init__(index=index, columns=columns)

        for i in index:
            data = {}
            for series in series_list:
                if i in series.index:
                    data[series.id] = series[i]
            self.set(indexes=i, values=data)
`

**Comment by rsheftel** [comment]
I don't think there is an elegant way to do this right now. Using the native functionality if you know you only have one column then this works:

```
import raccoon as rc

df1 = rc.DataFrame(data={'close': [9,8,7,6]}, index=[0,2,4,6], sort=True)
df2 = rc.DataFrame(data={'open': [1,2,3,4,5,6,7]}, index=[0, 1, 2, 3, 4, 5, 6], sort=True)

df1.set(df2.index, df2.columns[0], df2.data[0])
df1.show()

  index    close    open
-------  -------  ------
      0        9       1
      1                2
      2        8       3
      3                4
      4        7       5
      5                6
      6        6       7

```

If you have more than one column you could just run a loop that repeats the above for each column
