### ISSUE TITLE
The python code in the README is not rendering 

### ISSUE THREAD

**Issue by javadba** [rsheftel/raccoon#13]
.. but when going directly to https://github.com/rsheftel/raccoon/blob/master/docs/usage_dataframe.rst  the code *does* appear

**Comment by rsheftel** [comment]
What do you mean it is not rendering? The README renders properly in PyPi here: https://pypi.org/project/raccoon/

The docs are rendered on ReadTheDocs, here: https://raccoon.readthedocs.io/en/latest/

**Comment by javadba** [comment]
Here is an excerpt from https://media.readthedocs.org/pdf/raccoon/latest/raccoon.pdf

![image](https://user-images.githubusercontent.com/410769/46246003-3c676380-c3ac-11e8-919c-2dc935e8975e.png)

No *code* there ..

Instead here is the code  - from the link shown in the original post:

![image](https://user-images.githubusercontent.com/410769/46246026-789ac400-c3ac-11e8-9478-781d230a9519.png)

**Comment by rsheftel** [comment]
Aha, now I see. Probably an issue with ReadTheDocs. I will investiage

**Comment by rsheftel** [comment]
Thanks for pointing this out. It was an issue with ReadTheDocs and ipython. It has been corrected and pushed and the docs are now correct. Thanks again.
