### ISSUE TITLE
Question: does raccoon use the e.g. the bisect functions from the dropins?

### ISSUE THREAD

**Issue by bearsh** [rsheftel/raccoon#14]
looking at get_slice(): https://github.com/rsheftel/raccoon/blob/f1ea409143fa641cf75ae6af7f356f49413e46c1/raccoon/series.py#L184

there bisect_left from bisect is used. if blist is used as dropin it provides its own bisect_left implementation. but as far as I understand the code, this implementation is not used.

would it makes sense to query the list first if it provides a bisect function?

**Comment by rsheftel** [comment]
It would make sense if the performance net-net is better. If it materially degrades the base performance on the built in list implementation I would prefer to leave it as is. Can you run and find out?

**Comment by bearsh** [comment]
you are right.
I also had the assumption blist provides a bisect_x function but this is is only true for sortedlist and sorteddict...
so let's close it
