### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by tonycpsu** [rsheftel/raccoon#3]
Hi there, this is a neat project that might help me with something I'm working on that doesn't lend itself well to how Pandas works.  Problem is I do most of my work in Python 2.7.  It didn't take long for me to make your code 2.x compatible -- mostly just replaced some of the `list.copy()`s with `list[:]`s and removed the type hints.  If you're interested I can send a PR -- if not I'll just keep using what I have.

**Comment by tonycpsu** [comment]
Oh, and of course the `print()` method has to be renamed for py2 -- I made it `show()`.

**Comment by rsheftel** [comment]
Thanks for this. If you submit a pull request I will take a look. One question, why does the print() method need to be renamed? Does it conflict with something in python2.7?

**Comment by tonycpsu** [comment]
Yeah, `print` is a reserved keyword in Python < 3, just like `for`, `try`, and `yield`.

I'll send a PR your way.

Also, since you seem to be doing active development, are you taking feature requests?  One that jumps out to me is the seeming lack of a way to sort columns in reverse order, or according to a user-specified sort key / compare function.  Any plans to do that?

**Comment by rsheftel** [comment]
Thanks for all this. The project is an outgrowth of a larger project where I had a need for this pandas dataframe like data structure that was fast to expand. After searching everywhere and not able to find it I thought others might need it as well so I split that part out into this package.

So any development is mostly as needed in my larger project, but I am very happy to take that feature request or have anyone else add to the code base. My only request is that this code stay as fast as possible for the expanding dataframe use case.

**Comment by rsheftel** [comment]
I just made a Feature Request wiki page and added your suggestion.

**Comment by rsheftel** [comment]
Thanks for the PR #4 , it is merged into master

**Comment by tonycpsu** [comment]
Any idea what it takes to make raccoon available for Python 2 when installing with `pip`?  I see the [new release](https://pypi.python.org/pypi/raccoon) on PyPi and it's listed in the Python 2.7 category, but there's no build for 2.7 available, so it doesn't work unless I pip install from github.

**Comment by rsheftel** [comment]
I updated the setup.cfg to generate a universal wheel that will install on either python 2 or 3 and uploaded the new wheel to PyPi so "pip install raccoon" will work on either pip2 or pip3.
