### ISSUE TITLE
Bug in set_column index check

### ISSUE THREAD

**Issue by tonycpsu** [rsheftel/raccoon#5]
In `set_column`, I believe the following check is erroneous:

```python
    if len(index) == (index.count(True) + index.count(False)):  # boolean list
```

This works in most cases, but in the rare case where the index consists only of combinations of `0` and `1`, Python's quirky type system causes the code above to assume that what is being passed in is a boolean list when it's actually numeric IDs.  `1==True` and `0==False` are helpful in many cases, but not this one.

Something like:

```python
    if all([isinstance(i, bool) for i in index]):
```
Would probably do the right thing.

**Comment by rsheftel** [comment]
Thanks for this suggestion. Updated and committed.
